name: Bug report
description: File a bug report
title: "[Bug]: title"
labels: ["bug", "triage"]
body:
  - type: checkboxes
    attributes:
      label: Same issue exist?
      options:
        - label: I have searched the issues (https://github.com/dbkangaroo/kangaroo/issues)
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version of Kangaroo
      description: Which version of Kangaroo do you using?
      options:
        - 8.91.1
        - 8.90.1
        - 8.0.1
        - 7.99.1
        - 7.98.1
        - 6.99.1
        - 6.98.1
        - 6.4.1
        - 6.3.1
        - 6.2.1
        - 6.1.1
        - 6.0.1
        - others
    validations:
      required: true
  - type: dropdown
    id: branch
    attributes:
      label: Branch of Kangaroo
      description: Which branch of Kangaroo do you using?
      options:
        - Multiple
        - MariaDB
        - MongoDB
        - MySQL
        - Oracle
        - PostgreSQL
        - Redis
        - SQLite
        - SQLServer
        - AI Support
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platform of Kangaroo
      description: Which platform does Kangaroo run on it?
      options:
        - Windows (x86-64)
        - Windows (aarch64)
        - macOS (aarch64)
        - macOS (x86-64)
        - Linux (x86-64)
        - Linux (aarch64)
        - Linux (riscv64)
        - Linux (loongarch64)
        - Harmony (x86-64)
        - Harmony (aarch64)
        - Harmony (riscv64)
        - Harmony (loongarch64)
        - Others
    validations:
      required: true
  - type: input
    id: database
    attributes:
      label: Database system with name and version
      description: Please tell us the detail about database system
      placeholder: |
        <Database system> <Full version> <Collation>, ex: MySQL 8.0.28 utf8mb4_general_ci
    validations:
      required: false
  - type: textarea
    attributes:
      label: Bug detail
      description: Please share the bug environment, key steps, data and screenshot, expection and solution, thanks.
      placeholder: |
        1. Environment(CPU, OS, Database, etc)
        2. Reproduce steps
        3. Data and screenshot
        4. Expection and solution
    validations:
      required: true
